#!/bin/bash

file="$HOME/.cache/eww_bar"
cfg="$HOME/.config/eww/bar/"
EWW=$(which eww)

if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

run_eww() {
    ${EWW} --config "$cfg" open-many bar
}

if [[ ! -f "$file" ]]; then
    touch "$file"
    run_eww
else
    ${EWW} --config "$cfg" close bar
    rm -f "$file"
fi
