#!/bin/bash

file="$HOME/.cache/eww_bg"
cfg="$HOME/.config/eww/bg/"
EWW=$(which eww)

if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

run_eww() {
    ${EWW} --config "$cfg" open bg
}

if [[ ! -f "$file" ]]; then
    touch "$file"
    run_eww
else
    ${EWW} --config "$cfg" close bg
    rm -f "$file"
fi
